# Generated by Django 4.2 on 2023-07-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('username', models.CharField(blank=True, help_text='Username клиента', max_length=50, null=True, verbose_name='Username')),
                ('telegram_id', models.BigIntegerField(help_text='Telegram ID пользователя', verbose_name='Telegram ID')),
                ('name', models.CharField(help_text='Имя в Telegram', max_length=255, verbose_name='Имя в Telegram')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на пользователя')),
            ],
            options={
                'verbose_name': 'Клиенты телеграмм бота',
                'verbose_name_plural': 'Клиенты телеграмм бота',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SelectedDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions_id', models.IntegerField(help_text='ID избранного направления', verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Пользователь который добавил в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='telebot.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранные направления',
                'verbose_name_plural': 'Избранные направления',
            },
        ),
        migrations.CreateModel(
            name='ExchangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(help_text='Направление сделки', max_length=150, verbose_name='Направление')),
                ('exchange_id', models.IntegerField(help_text='ID обмена', verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Пользователь который совершил обмен', on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='telebot.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История обменов',
                'verbose_name_plural': 'История обменов',
            },
        ),
    ]
