# Generated by Django 4.2 on 2023-07-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteddestinations',
            name='directions_id',
        ),
        migrations.AddField(
            model_name='selecteddestinations',
            name='direction_id',
            field=models.CharField(default=1, help_text='ID избранного направления', max_length=10, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selecteddestinations',
            name='user',
            field=models.ForeignKey(help_text='Пользователь который добавил в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='telebot.client', verbose_name='Пользователь'),
        ),
    ]
