# Generated by Django 4.2 on 2023-08-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_remove_selecteddestinations_directions_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangehistory',
            options={'ordering': ('-created',), 'verbose_name': 'История обменов', 'verbose_name_plural': 'История обменов'},
        ),
        migrations.AddField(
            model_name='selecteddestinations',
            name='name',
            field=models.CharField(default='adadadad', help_text='Название избранного направления', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangehistory',
            name='user',
            field=models.ForeignKey(help_text='Пользователь который совершил обмен', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='telebot.client', verbose_name='Пользователь'),
        ),
    ]
